# config-management.yaml

apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  # clusterName is required and must be unique among all managed clusters
  clusterName: external-cluster-a
  git:
    syncRepo: https://github.com/bkauf/anthos-csm/
    secretType: none
    policyDir: "acme.org"
    syncBranch: 1.0.0
